---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuremanageddisk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: mysqlapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlapp
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqlvol
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: sample
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: Pooja@1122
      volumes:
        - name: mysqlvol
          persistentVolumeClaim: 
            claimName: azuremanageddisk
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
