---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: AzureManagedDisk
spec: 
  accessModes:
    - ReadWriteOnce
    storageClassName: default
    resources:
      requests:
        storage: 1Gi
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels: 
    app: mysqlapp
spec:
  selector:
    matchLabels:
      app: mysqlapp  
  template:
    metadata:
        labels:
        app: mysqlapp
    spec:
      containers:
        - image: mysql:8
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: sample
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: Pooja@0917
          volumeMounts:
            - name: mysqlvol
              mountPath: /var/lib/mysql
      volumes:
        -name: mysqlvol
        persistentVolumeClaim:
          claimName: AzureManagedDisk
      
          

